#!/usr/bin/env node
'use strict';

/**
 * Build assets/examples/all-diagrams-showcase.html from real package output.
 *
 * Every SVG in the page is produced by the same `renderMermaidSVG()` path the
 * CLI uses — no Mermaid.js CDN, no themeVariables approximation, no remote
 * runtime dependency. Preset switching toggles pre-rendered variants.
 */

const fs = require('fs');
const path = require('path');
const { renderSVG, PRESETS } = require('./lib/presets');

const SKILL_DIR = path.resolve(__dirname, '..');
const EXAMPLES = path.join(SKILL_DIR, 'assets', 'examples');
const OUT = path.join(EXAMPLES, 'all-diagrams-showcase.html');

const DIAGRAMS = [
  ['hero.mmd', 'State diagram', 'Craft reference fixture — metadata lives on edges.'],
  ['flowchart.mmd', 'Flowchart', 'Decision flow; conditions as edge labels.'],
  ['state.mmd', 'State diagram', 'Lifecycle with explicit start/end pseudostates.'],
  ['sequence.mmd', 'Sequence diagram', 'Request path across services.'],
  ['class.mmd', 'Class diagram', 'Type structure and relationships.'],
  ['er.mmd', 'ER diagram', 'Entities, keys and cardinality.'],
  ['xychart.mmd', 'XY chart', 'Sixth diagram family in 1.1.x.'],
  ['advanced-flowchart-subgraph.mmd', 'Flowchart + subgraphs', 'Stage grouping without color coding.'],
];

const PRESET_ORDER = ['craft', 'craft-dark', 'legacy'];

function pageCSS() {
  return `
:root { color-scheme: light; --page:#ffffff; --ink:#27272a; --muted:#71717a; --rule:#e4e4e7; }
body.preset-craft-dark, body.preset-legacy { color-scheme: dark; }
body.preset-craft-dark { --page:#18181b; --ink:#e4e4e7; --muted:#a1a1aa; --rule:#3f3f46; }
body.preset-legacy { --page:#1a1b26; --ink:#a9b1d6; --muted:#787c99; --rule:#2f3549; }
* { box-sizing: border-box; }
body {
  margin: 0; padding: 56px 24px 96px;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  background: var(--page); color: var(--ink);
}
main { max-width: 1100px; margin: 0 auto; }
h1 { font-size: 28px; font-weight: 600; margin: 0 0 8px; letter-spacing: -0.01em; }
p.lede { margin: 0 0 32px; color: var(--muted); font-size: 15px; max-width: 62ch; }
.switch { display: flex; gap: 8px; flex-wrap: wrap; margin-bottom: 40px; }
.switch button {
  font: inherit; font-size: 13px; padding: 7px 14px; border-radius: 6px;
  border: 1px solid var(--rule); background: transparent; color: var(--ink); cursor: pointer;
}
.switch button[aria-pressed="true"] { border-color: var(--ink); }
section { border-top: 1px solid var(--rule); padding: 32px 0 8px; }
h2 { font-size: 16px; font-weight: 600; margin: 0 0 4px; }
section p { margin: 0 0 20px; color: var(--muted); font-size: 13px; }
.frame { overflow-x: auto; }
svg { max-width: 100%; height: auto; display: block; }
.variant { display: none; }
body.preset-craft .variant[data-preset="craft"],
body.preset-craft-dark .variant[data-preset="craft-dark"],
body.preset-legacy .variant[data-preset="legacy"] { display: block; }
footer { margin-top: 56px; color: var(--muted); font-size: 12px; }
@media (max-width: 640px) { body { padding: 32px 16px 64px; } h1 { font-size: 22px; } }
`.trim();
}

async function main() {
  const sections = [];

  for (const [file, title, note] of DIAGRAMS) {
    const source = fs.readFileSync(path.join(EXAMPLES, file), 'utf8');
    const variants = [];
    for (const preset of PRESET_ORDER) {
      const { svg } = await renderSVG(source, { preset, offline: true });
      variants.push(`<div class="variant" data-preset="${preset}">${svg}</div>`);
    }
    sections.push(`  <section>
    <h2>${title} <span style="font-weight:400;color:var(--muted)">· ${file}</span></h2>
    <p>${note}</p>
    <div class="frame">
${variants.map((v) => `      ${v}`).join('\n')}
    </div>
  </section>`);
  }

  const buttons = PRESET_ORDER.map(
    (p, i) =>
      `      <button type="button" data-preset="${p}" aria-pressed="${i === 0}">${p} — ${PRESETS[p].description}</button>`
  ).join('\n');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>beautiful-mermaid — diagram showcase</title>
<style>
${pageCSS()}
</style>
</head>
<body class="preset-craft">
<main>
  <h1>beautiful-mermaid showcase</h1>
  <p class="lede">Every diagram below is pre-rendered by <code>renderMermaidSVG()</code> from the
  installed <code>beautiful-mermaid</code> package — the same path the CLI uses. No remote scripts,
  stylesheets or fonts. Regenerate with <code>node scripts/build_showcase.js</code>.</p>
  <div class="switch" role="group" aria-label="Preset">
${buttons}
  </div>
${sections.join('\n')}
  <footer>Generated by scripts/build_showcase.js · presets: ${PRESET_ORDER.join(', ')}</footer>
</main>
<script>
  document.querySelectorAll('.switch button').forEach(function (btn) {
    btn.addEventListener('click', function () {
      var preset = btn.dataset.preset;
      document.body.className = 'preset-' + preset;
      document.querySelectorAll('.switch button').forEach(function (b) {
        b.setAttribute('aria-pressed', String(b === btn));
      });
    });
  });
</script>
</body>
</html>
`;

  fs.writeFileSync(OUT, html, 'utf8');
  console.log(`Wrote ${OUT} (${DIAGRAMS.length} diagrams × ${PRESET_ORDER.length} presets)`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
